apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-pod-conf-depl
  labels:
      app: adv-pod-conf
spec:
  selector:
    matchLabels:
      app: adv-pod-conf
  replicas: 3
  template:
    metadata:
      labels:
        app: adv-pod-conf
    spec:
      containers:
      - name: adv-pod-conf-con
        image: fischerjulian/apc-demo-app:0.7.0
        ports:
          - containerPort: 4567
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SLEEP_ON_STARTUP
            value: "30"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4567            
          initialDelaySeconds: 35
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4567            
          initialDelaySeconds: 3
          periodSeconds: 3